#!/usr/bin/env bash

# Install HAProxy and dependencies
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy

# Enable HAProxy service
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAProxy to listen to web servers if not already configured
if ! grep -q "339475-web-01" /etc/haproxy/haproxy.cfg; then
    cat <<EOF >> /etc/haproxy/haproxy.cfg
listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 339475-web-01 3.85.168.15:80 check
   server 339475-web-02 100.27.13.191:80 check
EOF
fi

# Start HAProxy service
service haproxy start
